name: Update Action

on:
  - push
  - pull_request

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Update action file with new script urls
    runs-on: ubuntu-latest
    steps:
      - name: Update action.yml
        uses: techdevcenter/update-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref || github.ref_name }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          match: "{{ua_base_url}}"
